=== Yahya2e00l6/gtk4-final/schemas/ui-wrapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

  <xs:simpleType name="boolLike">
    <xs:restriction base="xs:string">
      <xs:enumeration value="true"/>
      <xs:enumeration value="false"/>
      <xs:enumeration value="1"/>
      <xs:enumeration value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="orientationType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="horizontal"/>
      <xs:enumeration value="vertical"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="alignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="start"/>
      <xs:enumeration value="center"/>
      <xs:enumeration value="end"/>
      <xs:enumeration value="fill"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="stackTransitionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none"/>
      <xs:enumeration value="crossfade"/>
      <xs:enumeration value="slide"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:attributeGroup name="commonStyleAttrs">
    <xs:attribute name="margin" type="xs:integer"/>
    <xs:attribute name="margin-top" type="xs:integer"/>
    <xs:attribute name="margin-bottom" type="xs:integer"/>
    <xs:attribute name="margin-start" type="xs:integer"/>
    <xs:attribute name="margin-end" type="xs:integer"/>
    <xs:attribute name="width" type="xs:integer"/>
    <xs:attribute name="height" type="xs:integer"/>
    <xs:attribute name="halign" type="alignType"/>
    <xs:attribute name="valign" type="alignType"/>
    <xs:attribute name="hexpand" type="boolLike"/>
    <xs:attribute name="vexpand" type="boolLike"/>
    <xs:attribute name="css-class" type="xs:string"/>
    <xs:attribute name="style-margin-top" type="xs:integer"/>
    <xs:attribute name="style-margin-bottom" type="xs:integer"/>
    <xs:attribute name="style-margin-start" type="xs:integer"/>
    <xs:attribute name="style-margin-end" type="xs:integer"/>
    <xs:attribute name="style-width" type="xs:integer"/>
    <xs:attribute name="style-height" type="xs:integer"/>
    <xs:attribute name="style-halign" type="alignType"/>
    <xs:attribute name="style-valign" type="alignType"/>
    <xs:attribute name="style-hexpand" type="boolLike"/>
    <xs:attribute name="style-vexpand" type="boolLike"/>
    <xs:attribute name="style-css-class" type="xs:string"/>
    <xs:attribute name="tooltip" type="xs:string"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="layoutAttrs">
    <xs:attribute name="col" type="xs:integer"/>
    <xs:attribute name="row" type="xs:integer"/>
    <xs:attribute name="colspan" type="xs:integer"/>
    <xs:attribute name="rowspan" type="xs:integer"/>
    <xs:attribute name="layout-col" type="xs:integer"/>
    <xs:attribute name="layout-row" type="xs:integer"/>
    <xs:attribute name="layout-colspan" type="xs:integer"/>
    <xs:attribute name="layout-rowspan" type="xs:integer"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="globalWidgetAttrs">
    <xs:attribute name="id" type="xs:string"/>
    <xs:attributeGroup ref="commonStyleAttrs"/>
    <xs:attributeGroup ref="layoutAttrs"/>
  </xs:attributeGroup>

  <xs:group name="widgetChildren">
    <xs:choice>
      <xs:element ref="box"/>
      <xs:element ref="grid"/>
      <xs:element ref="menubar"/>
      <xs:element ref="stack"/>
      <xs:element ref="stack-sidebar"/>
      <xs:element ref="button"/>
      <xs:element ref="entry"/>
      <xs:element ref="spin-button"/>
      <xs:element ref="dropdown"/>
      <xs:element ref="calendar"/>
      <xs:element ref="label"/>
      <xs:element ref="image"/>
      <xs:element ref="progress-bar"/>
      <xs:element ref="spinner"/>
      <xs:element ref="separator"/>
      <xs:element ref="checkbox"/>
      <xs:element ref="switch"/>
      <xs:element ref="radio-button"/>
    </xs:choice>
  </xs:group>

  <xs:complexType name="windowType">
    <xs:sequence>
      <xs:group ref="widgetChildren" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="title" type="xs:string"/>
    <xs:attribute name="icon-name" type="xs:string"/>
    <xs:attribute name="widget-name" type="xs:string"/>
    <xs:attribute name="background-image" type="xs:string"/>
    <xs:attribute name="default-width" type="xs:integer"/>
    <xs:attribute name="default-height" type="xs:integer"/>
    <xs:attribute name="min-width" type="xs:integer"/>
    <xs:attribute name="min-height" type="xs:integer"/>
    <xs:attribute name="max-width" type="xs:integer"/>
    <xs:attribute name="max-height" type="xs:integer"/>
    <xs:attribute name="resizable" type="boolLike"/>
    <xs:attribute name="decorated" type="boolLike"/>
    <xs:attribute name="modal" type="boolLike"/>
    <xs:attribute name="maximized" type="boolLike"/>
    <xs:attributeGroup ref="globalWidgetAttrs"/>
  </xs:complexType>

  <xs:complexType name="containerType">
    <xs:sequence>
      <xs:group ref="widgetChildren" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="globalWidgetAttrs"/>
  </xs:complexType>

  <xs:complexType name="leafType">
    <xs:attributeGroup ref="globalWidgetAttrs"/>
  </xs:complexType>

  <xs:element name="window" type="windowType"/>

  <xs:element name="box">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="containerType">
          <xs:attribute name="orientation" type="orientationType"/>
          <xs:attribute name="spacing" type="xs:integer"/>
          <xs:attribute name="homogeneous" type="boolLike"/>
          <xs:attribute name="align" type="alignType"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="grid">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="containerType">
          <xs:attribute name="column-spacing" type="xs:integer"/>
          <xs:attribute name="row-spacing" type="xs:integer"/>
          <xs:attribute name="homogeneous-columns" type="boolLike"/>
          <xs:attribute name="homogeneous-rows" type="boolLike"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="stack">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="stack-page" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="transition" type="stackTransitionType"/>
      <xs:attribute name="duration-ms" type="xs:integer"/>
      <xs:attribute name="vhomogeneous" type="boolLike"/>
      <xs:attribute name="hhomogeneous" type="boolLike"/>
      <xs:attributeGroup ref="globalWidgetAttrs"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="stack-sidebar">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="stack-id" type="xs:string" use="required"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="stack-page">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="widgetChildren" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="title" type="xs:string"/>
      <xs:attribute name="align" type="alignType"/>
      <xs:attributeGroup ref="globalWidgetAttrs"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="menubar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="menu-section" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="layout" type="orientationType"/>
      <xs:attribute name="show-arrow-indicators" type="boolLike"/>
      <xs:attributeGroup ref="globalWidgetAttrs"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="menu-section">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="menu-item" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="label" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="menu-item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="menu-item" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="label" type="xs:string" use="required"/>
      <xs:attribute name="enabled" type="boolLike"/>
      <xs:attribute name="on-activate" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="button">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="label" type="xs:string"/>
          <xs:attribute name="icon-name" type="xs:string"/>
          <xs:attribute name="theme-variant" type="xs:string"/>
          <xs:attribute name="use-underline" type="boolLike"/>
          <xs:attribute name="has-frame" type="boolLike"/>
          <xs:attribute name="can-shrink" type="boolLike"/>
          <xs:attribute name="icon-size" type="xs:integer"/>
          <xs:attribute name="on-clicked" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="entry">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="placeholder" type="xs:string"/>
          <xs:attribute name="default-text" type="xs:string"/>
          <xs:attribute name="purpose-hint" type="xs:string"/>
          <xs:attribute name="password" type="boolLike"/>
          <xs:attribute name="editable" type="boolLike"/>
          <xs:attribute name="max-length" type="xs:integer"/>
          <xs:attribute name="on-changed" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="spin-button">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="min" type="xs:decimal"/>
          <xs:attribute name="max" type="xs:decimal"/>
          <xs:attribute name="step" type="xs:decimal"/>
          <xs:attribute name="value" type="xs:decimal"/>
          <xs:attribute name="digits" type="xs:integer"/>
          <xs:attribute name="numeric-only" type="boolLike"/>
          <xs:attribute name="wrap" type="boolLike"/>
          <xs:attribute name="on-value-changed" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="dropdown">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="options" type="xs:string"/>
          <xs:attribute name="selected-index" type="xs:integer"/>
          <xs:attribute name="enable-search" type="boolLike"/>
          <xs:attribute name="on-selected" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="calendar">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="show-day-names" type="boolLike"/>
          <xs:attribute name="show-week-numbers" type="boolLike"/>
          <xs:attribute name="no-month-change" type="boolLike"/>
          <xs:attribute name="on-day-selected" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="label">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="text" type="xs:string"/>
          <xs:attribute name="selectable" type="boolLike"/>
          <xs:attribute name="wrap" type="boolLike"/>
          <xs:attribute name="max-width-chars" type="xs:integer"/>
          <xs:attribute name="ellipsize" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="image">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="icon-name" type="xs:string"/>
          <xs:attribute name="file-path" type="xs:string"/>
          <xs:attribute name="pixel-size" type="xs:integer"/>
          <xs:attribute name="keep-aspect" type="boolLike"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="progress-bar">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="fraction" type="xs:decimal"/>
          <xs:attribute name="text" type="xs:string"/>
          <xs:attribute name="show-text" type="boolLike"/>
          <xs:attribute name="inverted" type="boolLike"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="spinner">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="size" type="xs:integer"/>
          <xs:attribute name="spinning" type="boolLike"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="separator">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="orientation" type="orientationType"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="checkbox">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="label" type="xs:string"/>
          <xs:attribute name="active" type="boolLike"/>
          <xs:attribute name="inconsistent" type="boolLike"/>
          <xs:attribute name="on-toggled" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="switch">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="label" type="xs:string"/>
          <xs:attribute name="active" type="boolLike"/>
          <xs:attribute name="state" type="boolLike"/>
          <xs:attribute name="on-active-changed" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="radio-button">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="leafType">
          <xs:attribute name="label" type="xs:string"/>
          <xs:attribute name="group-with" type="xs:string"/>
          <xs:attribute name="is-active" type="boolLike"/>
          <xs:attribute name="on-toggled" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Yahya2e00l6/gtk4-final/examples/xml/demo_gallery.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../schemas/ui-wrapper.xsd"
        title="XML Demo - Gallery"
        icon-name="folder-pictures-symbolic"
        widget-name="wrapper-window"
        default-width="860"
        default-height="520"
        min-width="620"
        min-height="420"
        resizable="true"
        decorated="true">

  <box orientation="vertical"
       spacing="12"
       style-margin-top="14"
       style-margin-bottom="14"
       style-margin-start="14"
       style-margin-end="14"
       style-hexpand="true"
       style-vexpand="true">

    <label text="Media Gallery"
           style-css-class="title-2"
           style-margin-bottom="2" />
    <label text="Icons, file image, filters and controls in one XML layout." />

    <grid column-spacing="16"
          row-spacing="12"
          style-hexpand="true"
          style-vexpand="true">

      <box orientation="vertical"
           spacing="6"
           layout-col="0"
           layout-row="0">
        <label text="Icon Preview" />
        <image icon-name="applications-multimedia-symbolic" pixel-size="64" />
      </box>

      <box orientation="vertical"
           spacing="6"
           layout-col="1"
           layout-row="0">
        <label text="File Image Preview" />
        <image file-path="image.png" pixel-size="180" keep-aspect="true" />
      </box>

      <box orientation="vertical"
           spacing="8"
           layout-col="2"
           layout-row="0">
        <label text="Filters" />
        <dropdown options="All,Design,Code,Docs,Media"
                  enable-search="true"
                  style-width="180" />
        <entry placeholder="Search assets..." style-width="180" />
        <checkbox label="Favorites only" />
      </box>

      <separator orientation="horizontal"
                 layout-col="0"
                 layout-row="1"
                 layout-colspan="3"
                 style-margin-top="4"
                 style-margin-bottom="4" />

      <box orientation="horizontal"
           spacing="10"
           layout-col="0"
           layout-row="2"
           layout-colspan="3"
           style-halign="center">
        <button label="Previous" icon-name="go-previous-symbolic" />
        <button label="Play" icon-name="media-playback-start-symbolic" theme-variant="success" />
        <button label="Next" icon-name="go-next-symbolic" />
      </box>
    </grid>
  </box>
</window>

=== Yahya2e00l6/gtk4-final/examples/xml/layout_stress.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../schemas/ui-wrapper.xsd"
        title="Layout Stress XML"
        icon-name="applications-development-symbolic"
        default-width="980"
        default-height="760"
        resizable="true"
        decorated="true">

  <box orientation="vertical" spacing="18" margin="16" hexpand="true" vexpand="true">

    <label text="1) Same row: far left, centered, far right" css-class="title-2" halign="start" />
    <grid column-spacing="12" row-spacing="8" hexpand="true">
      <button label="LEFT" width="140" col="0" row="0" />
      <label text="CENTER" halign="center" hexpand="true" col="1" row="0" />
      <button label="RIGHT" width="140" halign="end" col="2" row="0" />
    </grid>

    <label text="2) Random grid positions and spans" css-class="title-2" halign="start" />
    <grid column-spacing="10" row-spacing="10" hexpand="true">
      <button label="0,0" width="90" col="0" row="0" />
      <button label="4,0" width="90" col="4" row="0" />
      <label text="spans 3 cols" css-class="title-1" halign="center" col="1" row="1" colspan="3" />
      <entry placeholder="wide entry at row 2" width="420" col="0" row="2" colspan="4" />
      <button label="tiny" width="70" col="4" row="2" />
      <checkbox label="lower-left" col="0" row="4" />
      <radio-button id="stress_a" label="A" col="2" row="4" />
      <radio-button label="B" group-with="stress_a" is-active="true" col="3" row="4" />
      <radio-button label="C" group-with="stress_a" col="4" row="4" />
    </grid>

    <label text="3) Margins: push individual widgets around" css-class="title-2" halign="start" />
    <box orientation="vertical" spacing="8">
      <button label="normal start" width="180" halign="start" />
      <button label="pushed right by margin-start=220" width="260" margin-start="220" halign="start" />
      <button label="aligned end" width="180" halign="end" />
      <button label="center + top margin" width="220" margin-top="18" halign="center" />
    </box>

    <label text="4) Mixed form: labels left, fields right" css-class="title-2" halign="start" />
    <grid column-spacing="12" row-spacing="10" halign="start">
      <label text="Name" col="0" row="0" />
      <entry placeholder="left field" width="220" col="1" row="0" />
      <label text="Score" col="3" row="0" />
      <spin-button min="0" max="20" value="12" width="90" col="4" row="0" />

      <label text="Choice" col="0" row="1" />
      <dropdown options="First,Second,Third" width="220" col="1" row="1" />
      <button label="Submit on far col" width="160" col="4" row="1" />
    </grid>

    <box orientation="horizontal" spacing="32" margin-top="16" halign="center">
      <button label="OK" icon-name="emblem-ok-symbolic" width="180" height="50" />
      <button label="Cancel" icon-name="window-close-symbolic" width="180" height="50" />
    </box>

  </box>
</window>

=== Yahya2e00l6/gtk4-final/examples/xml/demo_dashboard.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../schemas/ui-wrapper.xsd"
        title="XML Demo - Dashboard"
        icon-name="applications-system-symbolic"
        widget-name="wrapper-window"
        default-width="900"
        default-height="520"
        min-width="600"
        min-height="400"
        resizable="true"
        decorated="true"
        background-image="image.png">

  <box orientation="vertical"
       spacing="12"
       style-margin-top="12"
       style-margin-bottom="12"
       style-margin-start="12"
       style-margin-end="12"
       style-hexpand="true"
       style-vexpand="true">

    <label text="Ops Dashboard"
           style-css-class="title-2"
           style-margin-bottom="4" />

    <grid column-spacing="12"
          row-spacing="10"
          homogeneous-columns="true"
          style-hexpand="true"
          style-vexpand="true">

      <box orientation="vertical"
           spacing="6"
           layout-col="0"
           layout-row="0"
           style-margin-bottom="6">
        <label text="CPU" />
        <progress-bar fraction="0.66" text="66%" show-text="true" style-width="220" />
      </box>

      <box orientation="vertical"
           spacing="6"
           layout-col="1"
           layout-row="0"
           style-margin-bottom="6">
        <label text="Memory" />
        <progress-bar fraction="0.41" text="41%" show-text="true" style-width="220" />
      </box>

      <box orientation="vertical"
           spacing="6"
           layout-col="2"
           layout-row="0"
           style-margin-bottom="6">
        <label text="Network" />
        <progress-bar fraction="0.82" text="82%" show-text="true" style-width="220" />
      </box>

      <box orientation="vertical"
           spacing="8"
           layout-col="0"
           layout-row="1"
           style-margin-top="4">
        <label text="Status" />
        <spinner spinning="true" size="24" />
        <label text="Collector running" />
      </box>

      <box orientation="vertical"
           spacing="8"
           layout-col="1"
           layout-row="1"
           style-margin-top="4">
        <label text="Mode" />
        <radio-button id="mode_auto" label="Auto" is-active="true" />
        <radio-button label="Manual" group-with="mode_auto" />
      </box>

      <box orientation="vertical"
           spacing="8"
           layout-col="2"
           layout-row="1"
           style-margin-top="4">
        <label text="Quick Actions" />
        <button label="Refresh" icon-name="view-refresh-symbolic" theme-variant="primary" />
        <button label="Restart Agent" icon-name="system-run-symbolic" theme-variant="danger" />
      </box>
    </grid>
  </box>
</window>

=== Yahya2e00l6/gtk4-final/examples/xml/assignment_ui_short.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../schemas/ui-wrapper.xsd"
        title="Test des fonctions GTK+"
        icon-name="applications-development-symbolic"
        background-image="image2.png"
        default-width="900"
        default-height="900"
        min-width="760"
        min-height="720"
        resizable="true"
        decorated="true">

  <box orientation="vertical" spacing="16" margin="16" >
    
    <menubar halign="start">
      <menu-section label="MonChoix">
        <menu-item label="Sous Choix 1" on-activate="on_menu_about" />
        <menu-item label="Sous Choix2">
          <menu-item label="Choix221" on-activate="on_menu_about" />
          <menu-item label="Choix222" on-activate="on_menu_about" />
          <menu-item label="Choix223" on-activate="on_menu_about" />
        </menu-item>
        <menu-item label="Sous Choix3" on-activate="on_menu_about" />
      </menu-section>

      <menu-section label="VotreChoix">
        <menu-item label="Sous Choix 1" on-activate="on_menu_about" />
        <menu-item label="Sous Choix2">
          <menu-item label="Choix221" on-activate="on_menu_about" />
          <menu-item label="Choix222" on-activate="on_menu_about" />
          <menu-item label="Choix223" on-activate="on_menu_about" />
        </menu-item>
        <menu-item label="Sous Choix3" on-activate="on_menu_about" />
      </menu-section>

      <menu-section label="LeurChoix">
        <menu-item label="Sous Choix 1" on-activate="on_menu_about" />
        <menu-item label="Sous Choix2">
          <menu-item label="Choix221" on-activate="on_menu_about" />
          <menu-item label="Choix222" on-activate="on_menu_about" />
          <menu-item label="Choix223" on-activate="on_menu_about" />
        </menu-item>
        <menu-item label="Sous Choix3" on-activate="on_menu_about" />
      </menu-section>
    </menubar>

    <box orientation="vertical" spacing="4" margin="18" halign="center">
      <label text="Vos connaissances de GTK+" halign="center" />
      <box orientation="horizontal" spacing="18" halign="start">
        <radio-button id="knowledge_weak" label="Faible" />
        <radio-button label="Moyen" group-with="knowledge_weak" />
        <radio-button label="Bien" group-with="knowledge_weak" />
        <radio-button label="Très Bien" group-with="knowledge_weak" is-active="true" />
      </box>
    </box>

    <box orientation="vertical" spacing="4">
      <label text="Vos Commentaires sur GTK+" halign="start" />
      <box orientation="horizontal" spacing="18" halign="start">
        <checkbox label="Convivial" />
        <checkbox label="Intéressant" active="true" />
        <checkbox label="Facile à utiliser" />
        <checkbox label="Optimise le travail" />
      </box>
    </box>

    <grid column-spacing="10" row-spacing="10" margin-top="24" margin-start="18" halign="start">
      <label text="Zone de saisie" col="0" row="0" />
      <entry placeholder="Saisir un texte" width="280" col="1" row="0" colspan="4" />

      <label text="Choix de date" css-class="title-2" col="0" row="1" colspan="6" />

      <label text="Jour" col="0" row="2" />
      <spin-button min="1" max="31" step="1" value="1" numeric-only="true" width="80" col="1" row="2" />

      <label text="mois" col="2" row="2" />
      <spin-button min="0" max="12" step="1" value="0" numeric-only="true" width="80" col="3" row="2" />

      <label text="année" col="4" row="2" />
      <spin-button min="0" max="2100" step="1" value="0" numeric-only="true" width="100" col="5" row="2" />

      <dropdown options="Faire un choix,Choix 1,Choix 2,Choix 3" selected-index="0" width="240" col="0" row="3" colspan="3" />
    </grid>

    <button label="Afficher le dialogue"
            icon-name="dialog-warning-symbolic"
            width="260"
            margin-top="24"
            halign="center"
            on-clicked="on_show_dialog" />

    <box orientation="vertical" spacing="4" margin-start="360" halign="start">
      <label text="Le CoronaVirus" halign="start" />
      <box orientation="horizontal" spacing="12">
        <radio-button id="covid_sick" label="Malade" />
        <radio-button label="Suspect" group-with="covid_sick" />
        <radio-button label="Guéri" group-with="covid_sick" />
        <radio-button label="Sain" group-with="covid_sick" is-active="true" />
      </box>
    </box>

    <box orientation="horizontal" spacing="80" margin-top="24" halign="center">
      <button label="_OK"
              icon-name="emblem-ok-symbolic"
              use-underline="true"
              width="240"
              height="58"
              on-clicked="on_button_clicked" />
      <button label="Quitter"
              icon-name="application-exit-symbolic"
              width="240"
              height="58" />
    </box>

    <label id="status_label" text="Ready" margin-top="8" halign="start" />

  </box>
</window>
